apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: recruitment-service-deployment
  labels:
    app: recruitment-service-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        apps: recruitment-service
    spec:
      containers:
      - name: recruitment-service
        image: 47billion/hellonode:__BUILD_TAG__
        ports:
        - containerPort: 8081

